services:
  challenge-api:
    image: redteamsubnet61/flowradar-challenge:1.1.0
    build:
      context: ./src/flr_challenge/challenge
    # platform: linux/amd64
    privileged: true
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      FLR_API_PORT: ${FLR_API_PORT:-10001}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/configs/flowradar-challenge:${FLR_API_CONFIGS_DIR:-/etc/flowradar-challenge}"
      - "./volumes/storage/flowradar-challenge/logs:${FLR_API_LOGS_DIR:-/var/log/flowradar-challenge}"
      - "./volumes/storage/flowradar-challenge/data:${FLR_API_DATA_DIR:-/var/lib/flowradar-challenge}"
    ports:
      - "${FLR_API_PORT:-10001}:${FLR_API_PORT:-10001}"
    tty: true
